# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
exclude:
  [
    CNAME,
    README.md,
    LICENSE.md,
    .gitignore,
    package.json,
    yarn.lock,
    _js,
    _scss,
    _images,
    gulpfile.js,
    gulpconfig.js,
    node_modules,
    gemfile,
    Gemfile.lock,
    lint-staged.config.js,
    prettier.config.js,
  ]
permalink: /post/:title/
compress_html:
  clippings: all
  comments: all

# Site meta
title: 'Marc Reyes'
tagline: 'Software Engineer'
description: I'm <a href='/about'>Marc Reyes</a>, a Software Engineer focused on Web Dev, DevOps, and Data Science.
keywords: 'Marc Anthony Reyes, Marc Anthony, Marc Reyes, Projects, Marc Reyes Projects, Marc, Anthony, Reyes, Marc X, X, MX, M+X, Web Design, Website, Web Development, Web Dev, Freelancer, Speaking, Google, Google Developers, Code, Programming, Machine Learning'
url: https://marcreyes.ph
baseurl: 
assets: /assets
images: /images
image: index-large.jpg
logo: /assets/icons/apple-icon-144x144.png
dark_theme: false

author:
  name: Marc Reyes
  bio: I'm Marc Reyes, a Software Engineer focused on Web Development, DevOps, and Data Science from the Philippines.
  image: author
  url: https://marcreyes.ph
  email: hello@marcreyes.ph
  twitter: marcreyesph

social:
  twitter: https://twitter.com/marcreyesph
  instagram: https://instagram.com/marcxplanet
  github: https://github.com/connor-baer/marcreyesph
  medium: https://medium.com/@marcreyesph

version: 4.0.0

github:
  repo: https://github.com/marcreyesph/marcreyesph

# Integrations
# typekit:              fcv7rfe

# google_fonts:
#   Sharp Grotesk: 400, 600, 800

google_analytics_key: UA-94021817-2
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

# Content
excerpt_separator: <!-- Read more -->

navigation:
  GitHub: https://github.com/marcreyesph/marcreyesph
