name: Marc Reyes
hero_text: I'm Marc, a Software Engineer from the Philippines.
description: Building software, automating processes, and making data-driven decisions is what I enjoy most about my work. Currently working at <a class="link-1" href="https://gcash.com" target="_blank">GCash</a> as a Machine Learning Engineer.