# Site settings
email: marc@marcreyes.ph
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Blog
description: Blog by Marc Reyes
url: "https://blog.marcreyes.ph"
twitter_username: marcreyesph
default_img: https://assets-storage.marcreyes.ph/images/website-opengraph/1200x630-og-image.png/

# Profile settings
name: Marc Anthony Reyes
profile_img: /assets/images/marc-about-card.jpg
profile: Marc is currently a Computer Science student, freelance web developer, and Machine Learning engineer in the making based in Cagayan de Oro. Experimenting new developer tools and studying Machine Learning is his hobby. He has already talked in many developer events and is enthusiastic in sharing what he learned.
social:
  facebook: https://facebook.com/marcreyesph
  twitter: https://twitter.com/marcreyesph
  github: https://github.com/marcreyesph
  google-plus: https://plus.google.com/+marcreyesph

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
plugins: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
